const card=document.querySelector('#card'),bar=document.querySelector('#bar'),pct=document.querySelector('#pct');
let step=0,noTries=0,answers={},saleTimerInterval=null,activeDepositPrice='$74.99';
const screens=[
()=>`<div class="emoji">💌</div><div class="eyebrow">A very serious inquiry</div><h1>I have an important question.</h1><p>This should only take a minute. Probably.</p><div class="buttons"><button class="btn yes" onclick="next()">Continue →</button></div>`,
()=>`<div class="emoji">👀</div><div class="eyebrow">Question 01</div><h1>Would you go on a date with me?</h1><p>Please consider your options carefully. The website definitely isn't biased.</p><div class="buttons date-arena" id="arena"><button class="btn yes" onclick="next()">YES ❤️</button><button class="btn no" id="no">NO 🙄</button></div><div class="small" id="msg"></div>`,
()=>`<div class="emoji">🍝</div><div class="eyebrow">Question 02</div><h1>Wait… you said YES? 🥹</h1><p>I feel special now. So, what kind of date are we going on?</p><div class="grid"><button class="choice" onclick="chooseDateType('Dinner')">🍝 Dinner</button><button class="choice" onclick="chooseDateType('Activity')">🎳 Activity</button><button class="choice" onclick="chooseDateType('Adventure')">🌅 Adventure</button><button class="choice" onclick="chooseDateType('Surprise')">🎲 Surprise me</button></div>`,
()=>dateFollowUpScreen(),
()=>`<div class="emoji">🧐</div><div class="eyebrow">Question 03</div><h1>How much effort?</h1><p>There are only reasonable answers here.</p><div class="grid"><button class="choice" onclick="pick('effort','A lot')">A lot</button><button class="choice" onclick="pick('effort','Above and beyond')">Above and beyond</button><button class="choice" onclick="pick('effort','An unreasonable amount')">An unreasonable amount</button><button class="choice" onclick="pick('effort','Whatever it takes')">Whatever it takes</button></div>`,
()=>`<div class="emoji">💳</div><div class="eyebrow">Question 04</div><h1>You're asking them out… who pays?</h1><p>For clarity: <b>YOU</b> are the applicant asking someone else on this date.</p><div class="grid pay-grid"><button class="choice" id="mePay" onclick="chooseMePay(this)">I'M PAYING 😌</button><button class="choice" id="youPay" onclick="handleYouPay(this)">YOU'RE PAYING 👀</button></div><div class="small pay-message" id="payMsg"></div>`,
()=>`<div class="emoji">🏆</div><div class="eyebrow">Final decision</div><h1>Wait… WHAT? 🥹</h1><p>You want to ask me on a date <b>and</b> you're paying? I don't even know what to say.</p><h2 style="margin:0 0 18px">APPLICATION APPROVED. ❤️</h2><div class="buttons"><button class="btn yes" onclick="next()">Claim your date →</button></div>`,
()=>`<div class="emoji">📅</div><div class="eyebrow">Actual booking</div><h1>Okay, now actually pick when you're free.</h1><p>Today is allowed, but the earliest available time is always at least one hour from now.</p><div class="bookingFields"><label>Date<input id="date" type="date"></label><label>Time<select id="time"></select></label></div><div class="buttons"><button class="btn yes" onclick="book()">Book my date ❤️</button></div><div class="small" id="timeNote"></div>`,
()=>`<div class="emoji">💳</div><div class="eyebrow">Final step</div><h1>Date Reservation Deposit</h1><div class="small" style="margin:0 0 14px"><b>🔒 Card information is not saved or collected.</b><br>It is used only for local format validation on this page and is discarded immediately after submission.</div><div style="font-size:1.05rem;margin:4px 0 14px"><span id="originalPrice" style="text-decoration:line-through;opacity:.45">$99.99</span> <b id="depositPrice" style="font-size:1.55rem">$74.99</b><br><span class="small">Applicant promotional rate — Save $25</span></div><div class="timer"><div class="small">PRICE GUARANTEED FOR</div><div id="saleTimer">01:00</div></div><p>Enter your billing information to continue with your date reservation deposit.</p><label>Name on card<input id="cardname" autocomplete="off" placeholder="First Last" oninput="formatFullName(this)"></label><label>Card number<input id="cardnum" inputmode="numeric" autocomplete="off" maxlength="19" placeholder="4242 4242 4242 4242" oninput="formatCard(this)"></label><div class="grid"><label>Expiration<input id="exp" inputmode="numeric" autocomplete="off" maxlength="5" placeholder="MM/YY" oninput="formatExpiry(this)"></label><label>CVV<input id="cvv" inputmode="numeric" autocomplete="off" maxlength="3" placeholder="123" oninput="numbersOnly(this,3)"></label></div><label>Billing address<input id="addr" autocomplete="off" placeholder="Street address"></label><div class="grid"><label>City<input id="city" maxlength="40" placeholder="City" oninput="formatCity(this)"></label><label>ZIP<input id="zip" inputmode="numeric" maxlength="5" placeholder="ZIP code" oninput="numbersOnly(this,5)"></label></div><div class="buttons"><button class="btn yes" onclick="mockPay()"><span id="submitPrice">Submit $74.99 deposit ❤️</span></button></div><div class="small"><b>Refund Policy:</b> Available upon written request within 7–10 business dates.</div>`,
()=>`<div class="crop-line" aria-hidden="true"></div><section class="confirmation-card"><div class="emoji">🎟️</div><div class="eyebrow">Official date authorization</div><h1>DATE CONFIRMED.</h1><div class="ticket"><b>Applicant:</b> Approved Applicant<br><b>Date Privilege:</b> One (1) Date with Eligible Bachelor<br><b>Date Type:</b> <span id="tv"></span><br><b>Effort Level:</b> <span id="teffort"></span><br><span id="detailRow"><b>Date Choice:</b> <span id="tdd"></span><br></span><b>Date:</b> <span id="td"></span><br><b>Time:</b> <span id="tt"></span><br><b>Deposit:</b> <span id="finalDeposit"></span> <span id="depositStatus"></span><br><b>Application Status:</b> APPROVED ❤️</div></section><div class="crop-line bottom" aria-hidden="true"></div><section class="share-card"><b>📸 One last thing...</b><br><span class="small">Snap a picture or take a screenshot of your date confirmation and send it to the person you're trying to date. Crop the screenshot between the dashed lines above so only your official date confirmation is sent. ❤️</span></section>`];
function formatCity(e){e.value=e.value.replace(/[^A-Za-z\s]/g,'').replace(/\s+/g,' ').replace(/^\s/,'').slice(0,40)}
function formatFullName(e){e.value=e.value.replace(/[^A-Za-z\s]/g,'').replace(/\s+/g,' ').replace(/^\s/,'').split(' ').slice(0,3).join(' ')}
function numbersOnly(e,n){e.value=e.value.replace(/\D/g,'').slice(0,n)}
function formatExpiry(e){let t=e.value.replace(/\D/g,'').slice(0,4);e.value=t.length>=2?t.slice(0,2)+(t.length>2?'/'+t.slice(2):'/'):t}
function formatCard(e){e.value=e.value.replace(/\D/g,'').slice(0,16).replace(/(\d{4})(?=\d)/g,'$1 ')}
function lettersOnly(e){e.value=e.value.replace(/[^A-Za-z\s]/g,'').replace(/\s+/g,' ').replace(/^\s/,'').slice(0,60)}
function chooseDateType(v){answers.vibe=v;if(v==='Surprise'){answers.dateDetail='';step=4}else step=3;render()}
const dateOptions={
Dinner:{emoji:'🍽️',title:'What kind of dinner?',text:'Your culinary preferences have been noted by the selection committee.',options:[['🥩 Steakhouse','Steakhouse'],['🍝 Italian','Italian'],['🍣 Sushi','Sushi'],['🌮 Mexican','Mexican'],['🍔 Burgers','Burgers'],['🍕 Pizza','Pizza'],['🍤 Seafood','Seafood'],['🥢 Asian','Asian'],['🍜 Ramen','Ramen'],['🥘 Spanish','Spanish'],['🍗 Southern','Southern'],['🥗 Healthy','Healthy'],['🍳 Brunch','Brunch'],['🌊 Waterfront','Waterfront'],['🌇 Rooftop','Rooftop'],['✨ Fine dining','Fine dining'],['🍷 Wine bar','Wine bar'],['☕ Coffee and dessert','Coffee and dessert']]},
Activity:{emoji:'🎮',title:'What kind of activity?',text:'Choose how competitive you plan on being.',options:[['🕹️ Arcade','Arcade'],['🎳 Bowling','Bowling'],['⛳ Mini golf','Mini golf'],['🏎️ Go karts','Go karts'],['🎨 Painting or pottery','Painting or pottery'],['🎤 Karaoke','Karaoke'],['🧩 Escape room','Escape room'],['🎱 Billiards','Billiards'],['🪓 Axe throwing','Axe throwing'],['🧗 Rock climbing','Rock climbing'],['🛼 Roller skating','Roller skating'],['⛸️ Ice skating','Ice skating'],['🎯 Darts','Darts'],['🏹 Archery','Archery'],['🎲 Board games','Board games'],['🃏 Game night','Game night'],['🎭 Theater','Theater'],['😂 Comedy show','Comedy show'],['🎵 Live music','Live music'],['🎬 Movie','Movie'],['🏛️ Museum','Museum'],['🖼️ Art gallery','Art gallery'],['🍳 Cooking class','Cooking class'],['💃 Dance class','Dance class'],['🧁 Baking class','Baking class'],['☕ Cafe hopping','Cafe hopping'],['🍨 Dessert hopping','Dessert hopping'],['🛍️ Shopping','Shopping'],['📸 Photo walk','Photo walk'],['🎪 Festival or fair','Festival or fair']]},
Adventure:{emoji:'🌴',title:'What kind of adventure?',text:'Define “adventure” before things get carried away.',options:[['🏖️ Beach','Beach'],['🥾 Hiking or nature','Hiking or nature'],['🚤 Boat day','Boat day'],['🛶 Kayaking','Kayaking'],['🏄 Paddleboarding','Paddleboarding'],['🎣 Fishing','Fishing'],['🐎 Horseback riding','Horseback riding'],['🏕️ Camping','Camping'],['🌲 State park','State park'],['🌅 Sunset trip','Sunset trip'],['🎢 Theme park','Theme park'],['💦 Water park','Water park'],['🌆 Explore somewhere new','Explore somewhere new'],['🚗 Day trip','Day trip'],['🛣️ Road trip','Road trip'],['🏙️ City adventure','City adventure'],['🌴 Island day','Island day'],['🦁 Zoo or wildlife park','Zoo or wildlife park'],['🌌 Stargazing','Stargazing']]}};
function dateFollowUpScreen(){const x=dateOptions[answers.vibe];return `<div class="emoji">${x.emoji}</div><div class="eyebrow">Question 02B</div><h1>${x.title}</h1><p>${x.text}</p><div class="grid">${x.options.map(o=>`<button class="choice" onclick="pick('dateDetail','${o[1]}')">${o[0]}</button>`).join('')}<button class="choice" onclick="showOtherDateChoice()">✍️ Other</button></div><div id="otherChoice"></div>`}
function showOtherDateChoice(){const box=document.querySelector('#otherChoice');if(!box)return;box.innerHTML=`<label style="margin-top:14px">Other idea<input id="otherDateChoice" maxlength="60" placeholder="Type your idea" autocomplete="off" oninput="lettersOnly(this)"></label><div class="buttons"><button class="btn yes" onclick="saveOtherDateChoice()">Use this idea →</button></div>`;document.querySelector('#otherDateChoice')?.focus()}
function saveOtherDateChoice(){const e=document.querySelector('#otherDateChoice'),v=(e?.value||'').trim();if(!/^[A-Za-z]+(?: [A-Za-z]+)*$/.test(v))return alert('Use letters only for your date idea 👀');answers.dateDetail=v;step=4;render()}
function todayStr(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function setupBooking(){const d=document.querySelector('#date');if(!d)return;const today=todayStr();d.min=today;d.value=today;d.addEventListener('change',()=>{if(d.value<today){d.value=today;alert('Past dates are off limits.')}populateTimes()});populateTimes()}
function populateTimes(){const d=document.querySelector('#date'),s=document.querySelector('#time'),note=document.querySelector('#timeNote');if(!d||!s)return;const now=new Date(),today=todayStr();d.min=today;if(!d.value||d.value<today)d.value=today;s.innerHTML='';let first=540,end=1320;if(d.value===today)first=Math.max(first,Math.ceil((now.getHours()*60+now.getMinutes()+60)/30)*30);if(first>end){s.innerHTML='<option value="">No times left today</option>';if(note)note.textContent='It’s too late to book today — choose a future date.';return}for(let m=540;m<=end;m+=30){const h=Math.floor(m/60),min=m%60,ap=h>=12?'PM':'AM',label=`${h%12||12}:${String(min).padStart(2,'0')} ${ap}`,o=document.createElement('option');o.value=label;o.textContent=label;if(d.value===today&&m<first){o.disabled=true;o.textContent+=' — unavailable'}s.appendChild(o)}const f=[...s.options].find(o=>!o.disabled&&o.value);if(f)f.selected=true;if(note)note.textContent=d.value===today?'Today’s times start at least 1 hour from now.':'Available times: 9:00 AM–10:00 PM.'}
function book(){const d=document.querySelector('#date').value,t=document.querySelector('#time').value,today=todayStr();if(!d||d<today){alert('Past dates are off limits.');setupBooking();return}if(!t){alert('Pick an available time 👀');return}answers.date=d;answers.time=t;step=8;render()}
async function mockPay(){const name=document.querySelector('#cardname').value.trim(),num=document.querySelector('#cardnum').value.replace(/\D/g,''),exp=document.querySelector('#exp').value.trim(),cvv=document.querySelector('#cvv').value.replace(/\D/g,''),addr=document.querySelector('#addr').value.trim(),city=document.querySelector('#city').value.trim(),zip=document.querySelector('#zip').value.trim();if(!/^[A-Za-z]+ [A-Za-z]+(?: [A-Za-z]+)?$/.test(name)||num.length<13||!/\d{2}\/\d{2}/.test(exp)||cvv.length!==3||addr.length<4||!/^[A-Za-z]+(?: [A-Za-z]+)*$/.test(city)||zip.length!==5)return alert('Complete all billing fields in the requested format 👀');['cardname','cardnum','exp','cvv','addr','city','zip'].forEach(id=>document.getElementById(id).value='');const overlay=document.createElement('div');overlay.className='sendOverlay';overlay.innerHTML='<div><div class="envelope">💌</div><p><b>Finalizing your reservation…</b></p></div>';card.appendChild(overlay);setTimeout(()=>{step=9;render();confetti()},1350)}
function fillConfirmation(){const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=v};set('#tv',answers.vibe==='Surprise'?'Surprise me':answers.vibe||'—');set('#teffort',answers.effort||'—');const row=document.querySelector('#detailRow');if(answers.dateDetail){set('#tdd',answers.dateDetail);if(row)row.style.display=''}else if(row)row.style.display='none';set('#td',answers.date?new Date(answers.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}):'—');set('#tt',answers.time||'—');set('#finalDeposit',activeDepositPrice||'—');set('#depositStatus',activeDepositPrice==='$74.99'?'(Discounted 🎉)':'(Not discounted 😬)')}
function startSaleTimer(){saleTimerInterval&&clearInterval(saleTimerInterval);activeDepositPrice='$74.99';let seconds=60,timer=document.querySelector('#saleTimer');const tick=()=>{if(!timer)return;timer.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');if(seconds<=0){clearInterval(saleTimerInterval);timer.textContent='OFFER EXPIRED';activeDepositPrice='$201.72';const p=document.querySelector('#depositPrice'),o=document.querySelector('#originalPrice'),b=document.querySelector('#submitPrice');if(p)p.textContent='$201.72';if(o){o.style.textDecoration='none';o.style.opacity='1'}if(b)b.textContent='Submit $201.72 deposit ❤️';const label=p?.parentElement?.querySelector('.small');if(label)label.textContent='Standard rate + 169% late applicant markup';return}seconds--};tick();saleTimerInterval=setInterval(tick,1000)}
function render(){card.classList.toggle('confirmation-layout',step===9);card.innerHTML=screens[step]();const progress=Math.min(100,Math.round(step/(screens.length-1)*100));bar.style.width=progress+'%';pct.textContent=progress+'%';if(step===1)setupNo();if(step===7)setupBooking();if(step===8)startSaleTimer();if(step===9)fillConfirmation()}
function next(){step++;render()}
function pick(k,v){answers[k]=v;step++;render()}
function isTouchMobile(){return navigator.maxTouchPoints>0||('ontouchstart' in window)}
function chooseMePay(btn){answers.pay='Me';const msg=document.querySelector('#payMsg');if(msg)msg.textContent='Excellent financial judgment. Application strengthened. 📈';btn.classList.add('pay-approved');setTimeout(()=>{step=6;render()},750)}
function handleYouPay(btn){const me=document.querySelector('#mePay'),msg=document.querySelector('#payMsg'),tries=Number(btn.dataset.tries||0)+1;btn.dataset.tries=tries;if(me){me.classList.add('pay-nudge');me.style.transform=`scale(${Math.min(1.16,1+tries*.055)})`}if(tries===1){btn.textContent='I’M PAYING TOO 😌';if(msg)msg.textContent='Exactly. You asked them out. 😂';return}if(tries===2){btn.textContent='I’M DEFINITELY PAYING 😂';if(msg)msg.textContent='There we go. Financial responsibility accepted.';return}answers.pay='Me';if(msg)msg.textContent='Excellent choice. Applicant pays. 😂';setTimeout(()=>{step=6;render()},650)}
function setupNo(){const no=document.querySelector('#no'),arena=document.querySelector('#arena'),msg=document.querySelector('#msg'),yes=arena.querySelector('.yes');if(!no||!arena)return;const messages=['Nice try 😂','Oh, so we’re playing games now?','You really thought that would work?','Wrong button, beautiful.','I admire the commitment 😂','Okay, that one was close.','Not you trying again 💀','You’re making this harder than it needs to be.','I know you see the YES button.','That button is clearly avoiding you.','You almost got it 😂','Still trying? I respect it.','At this point, just say yes.','The button said “not today.”','Oh, you’re stubborn stubborn.','Caught you trying again 👀','You and this NO button need to let it go.','We can do this all day 😂','You’re definitely doing this on purpose now.','Okay troublemaker, pick YES.','That was a respectable attempt.','I’m starting to think you enjoy chasing it.','The answer you’re looking for is on the left.','Don’t worry, I’ll wait 😂','One of us is eventually going to win this.'];let last=-1;function flee(ev){if(ev)ev.preventDefault();noTries++;if(yes){const maxWidth=Math.max(yes.offsetWidth,arena.clientWidth-24),nextWidth=Math.min(maxWidth,yes.offsetWidth+Math.max(12,arena.clientWidth*.055)),baseHeight=parseFloat(yes.dataset.baseHeight)||yes.offsetHeight,maxHeight=Math.min(118,baseHeight*2.05),nextHeight=Math.min(maxHeight,baseHeight+noTries*6);yes.dataset.baseHeight=baseHeight;yes.style.width=nextWidth+'px';yes.style.height=nextHeight+'px';yes.style.maxWidth='calc(100% - 24px)';yes.style.transition='width .2s ease,height .2s ease';if(noTries===3)yes.classList.add('yes-attention')}const ar=arena.getBoundingClientRect(),nr=no.getBoundingClientRect(),pad=8,maxX=Math.max(pad,ar.width-nr.width-pad),safeTop=Math.min(ar.height-nr.height-pad,Math.max(82,ar.height*.58)),maxY=Math.max(safeTop,ar.height-nr.height-pad);no.style.position='absolute';no.style.margin='0';no.style.left=(pad+Math.random()*Math.max(0,maxX-pad))+'px';no.style.right='auto';no.style.top=(safeTop+Math.random()*Math.max(0,maxY-safeTop))+'px';let i;do{i=Math.floor(Math.random()*messages.length)}while(i===last&&messages.length>1);last=i;if(msg)msg.textContent=messages[i]}no.addEventListener('pointerenter',flee);no.addEventListener('pointerdown',flee)}
function confetti(){for(let i=0;i<24;i++){const s=document.createElement('span');s.textContent=['❤️','✨','💌'][i%3];s.style.cssText=`position:fixed;left:${Math.random()*100}vw;top:-30px;font-size:${14+Math.random()*18}px;z-index:9999;pointer-events:none;transition:transform 1.6s ease-in,opacity 1.6s`;document.body.appendChild(s);requestAnimationFrame(()=>{s.style.transform=`translateY(110vh) rotate(${Math.random()*720}deg)`;s.style.opacity='0'});setTimeout(()=>s.remove(),1700)}}
render();