function populateTimes(){const dateInput=document.querySelector('#date'),select=document.querySelector('#time'),note=document.querySelector('#timeNote');if(!dateInput||!select)return;select.innerHTML='';const now=new Date(),today=todayStr();let firstAllowed=9*60,end=22*60;if(dateInput.value===today){const minAllowed=now.getHours()*60+now.getMinutes()+60;firstAllowed=Math.max(firstAllowed,Math.ceil(minAllowed/30)*30)}if(firstAllowed>end){select.innerHTML='<option value="">No times left today</option>';note.textContent='It’s too late to book today — choose a future date.';return}for(let mins=9*60;mins<=end;mins+=30){const h=Math.floor(mins/60),mm=mins%60,ap=h>=12?'PM':'AM',hh=h%12||12,label=`${hh}:${String(mm).padStart(2,'0')} ${ap}`,opt=document.createElement('option');opt.value=label;opt.textContent=label;if(dateInput.value===today&&mins<firstAllowed){opt.disabled=true;opt.textContent=label+' — unavailable'}select.appendChild(opt)}const first=[...select.options].find(o=>!o.disabled&&o.value);if(first)first.selected=true;note.textContent=dateInput.value===today?'Today’s times start at least 1 hour from now.':'Available times: 9:00 AM–10:00 PM.'}function book(){const d=document.querySelector('#date').value,t=document.querySelector('#time').value;if(!d){alert('Pick a date first 👀');return}const now=new Date(),today=todayStr();if(d<today){alert('Past dates are off limits.');return}if(!t){alert('Pick an available time 👀');return}if(d===today){const m=t.match(/(\d+):(\d+) (AM|PM)/);let hour=Number(m[1])%12+(m[3]==='PM'?12:0),minute=Number(m[2]);const chosen=new Date(now.getFullYear(),now.getMonth(),now.getDate(),hour,minute);if(chosen.getTime()-now.getTime()<60*60*1000){alert('Today needs at least 1 hour of notice.');populateTimes();return}}answers.date=d;answers.time=t;step++;render()}

/* Skip the phone-number screen entirely. No phone number is requested or used. */
const originalPick=pick;
pick=function(key,value){answers[key]=value;if(step===5){step=7;render();return}step++;render()};
handleYouPay=function(btn){if(isTouchMobile()){if(btn.dataset.armed==='1'){answers.pay='Me';step=7;render();return}btn.dataset.armed='1';btn.textContent='Also me';btn.setAttribute('aria-label','Also me. Tap again to continue.');return}answers.pay='You';step=7;render()};
sendSMS=async function(){return{success:false,skipped:true}};

/* Keep the fleeing NO button in a separate safe zone below YES. */
setupNo=function(){const no=document.querySelector('#no'),arena=document.querySelector('#arena'),msg=document.querySelector('#msg');if(!no||!arena)return;const messages=['Nice try','Really?',"You're persistent.",'Wrong button →','This thing may be rigged.'];function flee(ev){if(ev)ev.preventDefault();noTries++;const ar=arena.getBoundingClientRect(),nr=no.getBoundingClientRect();const pad=8,maxX=Math.max(pad,ar.width-nr.width-pad);const safeTop=Math.min(ar.height-nr.height-pad,Math.max(82,ar.height*.58));const maxY=Math.max(safeTop,ar.height-nr.height-pad);const x=pad+Math.random()*Math.max(0,maxX-pad);const y=safeTop+Math.random()*Math.max(0,maxY-safeTop);no.style.position='absolute';no.style.margin='0';no.style.left=x+'px';no.style.right='auto';no.style.top=y+'px';if(msg)msg.textContent=messages[Math.min(noTries-1,messages.length-1)]}no.addEventListener('pointerenter',flee);no.addEventListener('pointerdown',flee)};